-- Add AgentiLab Widget Library project
-- URL: https://widget-hub.app
-- Date: October 15, 2025

INSERT INTO projects (slug, title, description, tech, image, overview, features, live_url)
VALUES (
  'widget-hub',
  'AgentiLab Widget Library - Premium Embeddable Widgets',
  'Premium widget library providing embeddable, real-time data widgets for any website. Universal widgets including population counters, weather displays, cryptocurrency tickers, AI-generated quotes, and world clocks. Simple HTML integration with consistent AgentiLab.ai branding and tech-premium aesthetic.',
  ARRAY['React 18', 'TypeScript', 'Express', 'OpenAI GPT-5', 'PostgreSQL', 'Drizzle ORM', 'shadcn/ui', 'TailwindCSS', 'Vite', 'TanStack Query', 'Real-time Data'],
  'https://raw.githubusercontent.com/simonpierreboucher02/app-image/main/widget-hub-image.png',
  '# AgentiLab Widget Library - Premium Embeddable Widgets

## Overview

AgentiLab Widget Library is a premium platform that delivers embeddable, real-time data widgets for any website. The platform offers a curated collection of universal widgets including population counters, live weather displays, cryptocurrency tickers, AI-generated quotes, and world clocks. Users can seamlessly integrate these widgets into their websites using simple HTML snippets, with all widgets featuring consistent "Generated by AgentiLab.ai" branding.

## Core Capabilities

The platform enables users to:
- **Embed Real-Time Widgets** with simple HTML snippets
- **Display Live Data** from population, weather, crypto, and more
- **AI-Generated Content** with GPT-5 powered inspirational quotes
- **Universal Integration** compatible with any website or CMS
- **Premium Design** with tech-inspired aesthetic (Linear, Vercel, Stripe)
- **Mobile-Responsive** widgets that adapt to any screen size

## Technical Architecture

### Frontend Stack
- **React 18** with TypeScript for type-safe widget applications
- **Vite** for fast HMR and optimized production builds
- **shadcn/ui** (New York variant) for consistent, accessible UI components
- **Radix UI** primitives for complex interactive components
- **TailwindCSS** for utility-first styling with custom design tokens
- **TanStack Query v5** for server state management with automatic caching
- **Wouter** for lightweight client-side routing
- **Class Variance Authority** for type-safe component variants

### Backend Architecture
- **Express.js** with TypeScript running on Node.js
- **RESTful API** design serving JSON data for widgets
- **In-memory caching** with custom MemStorage class and TTL
- **PostgreSQL (Neon)** with Drizzle ORM for data persistence
- **OpenAI GPT-5** via Replit AI Integrations for quote generation
- **Real-time calculations** for dynamic data like population counters

### Design System

**Tech-Premium Aesthetic**
- Inspired by Linear, Vercel, and Stripe design languages
- Data-first clarity with information hierarchy
- Dark mode primary with light mode support
- Mobile-first responsive approach

**Typography**
- **Inter font** for UI and body text
- **JetBrains Mono** for data displays and monospace content
- Clear visual hierarchy for data presentation

**Color Palette**
- HSL-based custom color tokens for theme consistency
- Dark backgrounds with high-contrast data displays
- Subtle animations and transitions
- Consistent widget branding

## Widget Collection

### 1. Population Counter Widget

Real-time world population display:

**Features:**
- **Live Population Count** - Real-time calculation based on birth/death rates
- **Birth/Death Counters** - Running counters for births and deaths today
- **Rate Statistics** - Births and deaths per second/minute/day
- **Smooth Animations** - Client-side interpolation for seamless counting
- **Reference Timestamp** - Mathematical calculations from base population data

**Technical Implementation:**
```javascript
// Population calculation algorithm
const currentPopulation = basePopulation + 
  (birthRate - deathRate) * secondsSinceReference;
```

**Data Refresh:**
- Real-time calculation without caching
- Client-side updates every second
- Server provides accurate rates and base data

### 2. Weather Widget

Location-based weather information:

**Features:**
- **Current Temperature** - Real-time temperature display
- **Weather Conditions** - Icon and text description (sunny, cloudy, rainy)
- **Location Data** - City and country information
- **Humidity Levels** - Percentage humidity display
- **Weather Icons** - Visual condition indicators
- **Auto-refresh** - Updates every 5 minutes

**Data Sources:**
- Third-party weather API integration
- Location-based data retrieval
- 5-minute cache for performance

### 3. Cryptocurrency Ticker Widget

Live crypto price tracking:

**Features:**
- **Real-Time Prices** - Current cryptocurrency values
- **24h Change** - Price change percentage with color indicators
- **Multiple Coins** - Bitcoin, Ethereum, and major altcoins
- **Sparkline Charts** - Mini price trend visualizations
- **Price Alerts** - Visual indicators for significant changes
- **Symbol Display** - Crypto ticker symbols (BTC, ETH, etc.)

**Data Refresh:**
- 1-minute cache for volatile crypto data
- Real-time price feeds integration
- Color-coded gains (green) and losses (red)

### 4. AI Quote Generator Widget

GPT-5 powered inspirational quotes:

**Features:**
- **AI-Generated Quotes** - Unique inspirational quotes about AI and technology
- **Author Attribution** - AI-generated author names
- **Category Tags** - Organized by themes (motivation, innovation, future)
- **OpenAI GPT-5** - Latest language model for creative content
- **JSON Structure** - Consistent data format for parsing
- **On-Demand Generation** - Fresh quotes generated per request

**Quote Examples:**
```json
{
  "text": "The future belongs to those who believe in the beauty of AI innovation",
  "author": "Digital Visionary",
  "category": "innovation"
}
```

### 5. World Clock Widget

Multi-timezone time display:

**Features:**
- **Multiple Timezones** - Display time across different regions
- **City Labels** - Major cities with timezone information
- **12/24 Hour Format** - User preference support
- **Auto-Update** - Real-time clock synchronization
- **DST Support** - Automatic daylight saving time adjustment
- **Timezone Offset** - Clear UTC offset display

**Supported Regions:**
- New York (EST/EDT)
- London (GMT/BST)
- Tokyo (JST)
- Sydney (AEST/AEDT)
- Dubai (GST)
- Los Angeles (PST/PDT)

## Widget Integration System

### Simple HTML Embedding

Easy integration for any website:

**Step 1: Copy Widget Code**
```html
<div id="agentilab-widget-population"></div>
<script src="https://widget-hub.app/embed/population.js"></script>
```

**Step 2: Paste into Website**
- WordPress, Shopify, Wix compatible
- Works with static HTML sites
- CMS-agnostic integration
- No backend configuration needed

**Step 3: Customize (Optional)**
```html
<script>
  AgentiLabWidget.init({
    widget: "population",
    theme: "dark",
    size: "medium"
  });
</script>
```

### Widget Customization Options

**Theme Variants:**
- Dark mode (default)
- Light mode
- Auto (follows system preference)

**Size Options:**
- Small (compact display)
- Medium (balanced layout)
- Large (detailed view)

**Update Intervals:**
- Configurable refresh rates
- Data-appropriate defaults
- Manual refresh control

### API Endpoints

RESTful widget data APIs:

**Population Data**
```
GET /api/widgets/population
Response: {
  current: 8000000000,
  birthRate: 4.3,
  deathRate: 1.8,
  timestamp: "2025-10-15T..."
}
```

**Weather Data**
```
GET /api/widgets/weather
Response: {
  location: "New York, US",
  temperature: 72,
  condition: "sunny",
  humidity: 45
}
```

**Crypto Data**
```
GET /api/widgets/crypto
Response: [{
  symbol: "BTC",
  price: 65000,
  change24h: 2.5,
  sparkline: [...]
}]
```

**Quote Data**
```
GET /api/widgets/quote
Response: {
  text: "AI quote...",
  author: "Author",
  category: "innovation"
}
```

**World Clock Data**
```
GET /api/widgets/clock
Response: [{
  city: "New York",
  timezone: "America/New_York",
  time: "14:30:00",
  offset: "-04:00"
}]
```

## Caching Strategy

### Intelligent Cache Management

**TTL-Based Caching:**
- **Weather:** 5-minute cache (stable data)
- **Crypto:** 1-minute cache (volatile data)
- **Population:** Real-time calculation (no cache)
- **Quotes:** On-demand generation (no cache)
- **World Clock:** Real-time calculation (no cache)

**Cache Implementation:**
```typescript
class MemStorage {
  private cache: Map<string, CachedData>;
  
  get(key: string, ttl: number): Data | null {
    const cached = this.cache.get(key);
    if (cached && Date.now() - cached.timestamp < ttl) {
      return cached.data;
    }
    return null;
  }
}
```

**Benefits:**
- Reduced API calls to external services
- Improved response times
- Cost optimization for paid APIs
- Fresh data when needed

## Data Models

### TypeScript Schemas with Zod

**Population Data Schema:**
```typescript
const PopulationData = z.object({
  current: z.number(),
  birthRate: z.number(),
  deathRate: z.number(),
  timestamp: z.string().datetime()
});
```

**Weather Data Schema:**
```typescript
const WeatherData = z.object({
  location: z.string(),
  temperature: z.number(),
  condition: z.string(),
  humidity: z.number()
});
```

**Crypto Data Schema:**
```typescript
const CryptoData = z.object({
  symbol: z.string(),
  price: z.number(),
  change24h: z.number(),
  sparkline: z.array(z.number())
});
```

## Branding & Compliance

### Consistent Widget Attribution

**"Generated by AgentiLab.ai"**
- Displayed on all widget types
- Subtle, non-intrusive placement
- Clickable link to AgentiLab.ai
- Premium branding design
- White-label option (premium tier - future)

### Widget Standards

**Responsive Design:**
- Mobile-first approach
- Adapts to container width
- Touch-friendly interactions
- Readable on all screen sizes

**Accessibility:**
- WCAG 2.1 AA compliant
- Keyboard navigation support
- Screen reader friendly
- High contrast options

**Performance:**
- Lightweight JavaScript (<50KB)
- Lazy loading for images
- Efficient DOM updates
- Minimal network requests

## Use Cases & Applications

### Business Websites
- Real-time data displays for credibility
- Live cryptocurrency prices for fintech sites
- Weather widgets for travel/hospitality
- Inspirational quotes for coaching/productivity sites

### News & Media
- Population statistics for articles
- World clock for international news
- Crypto tickers for financial news
- Real-time data visualization

### Educational Platforms
- Population growth demonstrations
- Timezone education tools
- Cryptocurrency learning resources
- Data science visualizations

### Personal Blogs
- Tech-focused content enhancement
- Data-driven storytelling
- Interactive reader engagement
- Professional aesthetic

## Development & Deployment

### Build Process

**Development Mode:**
- Vite dev server with HMR
- TSX for TypeScript server hot reload
- Middleware-based Vite integration

**Production Mode:**
- Static frontend built to `dist/public`
- Server bundle compiled to `dist/index.js`
- Express serves static files and API routes

### Environment Configuration

**Required Variables:**
- `NODE_ENV` - Environment detection
- `DATABASE_URL` - PostgreSQL connection
- `AI_INTEGRATIONS_OPENAI_BASE_URL` - AI service URL
- `AI_INTEGRATIONS_OPENAI_API_KEY` - OpenAI API key

### Database Management

**Drizzle ORM:**
- Schema in TypeScript (`./shared/schema.ts`)
- Zod validation for type safety
- Neon serverless PostgreSQL driver
- Migrations via Drizzle Kit

## Future Enhancements

### Planned Features
- Stock market widgets (S&P 500, NASDAQ)
- News headline widgets with AI summarization
- Social media metrics widgets
- Custom widget builder interface
- White-label premium tier
- Analytics dashboard for widget usage
- Webhook support for real-time updates
- Widget marketplace for community widgets',
  ARRAY[
    'Population Counter Widget - Real-time world population with birth/death rates and smooth animations',
    'Weather Widget - Location-based temperature, conditions, humidity with 5-minute auto-refresh',
    'Cryptocurrency Ticker - Live Bitcoin, Ethereum prices with 24h change and sparkline charts',
    'AI Quote Generator - GPT-5 powered inspirational quotes about AI and technology',
    'World Clock Widget - Multi-timezone time display with DST support and UTC offsets',
    'Simple HTML Integration - One-line embed code compatible with any website or CMS',
    'Premium Design System - Tech-inspired aesthetic (Linear, Vercel, Stripe) with dark/light modes',
    'Real-Time Data Streaming - Live updates with client-side interpolation for smooth counters',
    'Intelligent Caching - TTL-based strategy (weather 5min, crypto 1min) for optimal performance',
    'RESTful Widget APIs - JSON endpoints for all widget data with Zod schema validation',
    'Mobile-First Responsive - Adapts to any screen size with touch-optimized interactions',
    'AgentiLab Branding - Consistent "Generated by AgentiLab.ai" attribution on all widgets',
    'TypeScript Type Safety - Full type coverage with Zod validation and Drizzle ORM',
    'Theme Customization - Dark mode, light mode, auto theme with size options (small/medium/large)',
    'TanStack Query Integration - Automatic caching, refetching, and error handling',
    'shadcn/ui Components - Accessible, consistent UI with Radix UI primitives',
    'Mathematical Calculations - Real-time population counter using birth/death rate algorithms',
    'OpenAI GPT-5 Integration - On-demand quote generation with structured JSON responses',
    'WCAG 2.1 AA Compliance - Keyboard navigation, screen reader support, high contrast',
    'Lightweight Performance - <50KB JavaScript, lazy loading, efficient DOM updates'
  ],
  'https://widget-hub.app'
);
